name: dev-pipeline

on:
  workflow_dispatch:

jobs:
  terraform-int:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Check repository files
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -type f -name "*.tf"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate