name: dev-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - Prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_ENV: ${{ github.event.inputs.environment || 'qa' }}

      environment: ${{ github.event.inputs.environment || 'qa' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Show environment
        run: |
          echo "Running Terraform for: $TF_ENV"
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform apply
        working-directory: ./terraform  
        run: terraform apply -auto-approve tfplan

      - name: Terraform destroy
        if: ${{ github.event.inputs.environment == 'dev' }}
        working-directory: ./terraform
        run: terraform destroy -auto-approve
